### ISSUE TITLE
Wrong (memap) output

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/oob-mbed-os-example-client#8] opened 2016-10-11 16:48 UTC
Memap is not generating correct / consistent output.
This is the output I get from`mbed ls`, and I'd expect something similar in memap.

```
> mbed ls
oob-mbed-os-example-client (d9f9879e067e)
|- atmel-rf-driver (62c0c49d7a94)
|- esp8266-driver (dc37b65ca877)
|- mbed-client (1c03b36ac944)
|  |- mbed-client-classic (656f13cd4864)
|  `- mbed-client-mbed-tls (7e1b6d815038)
|- mbed-os (a551faa88151)
|- mcr20a-rf-driver (d8810e105d7d)
`- pal (797a41b1ec7d)
```

- *GCC*
 - Program files path? what is it for?
 - Features / drivers? It's not being shown

```
+------------------------+--------+-------+-------+
| Module                 |  .text | .data |  .bss |
+------------------------+--------+-------+-------+
| .build/K64F            | 174968 |   302 | 26571 |
| Fill                   |    518 |    14 |  2533 |
| c:/program files (x86) |    232 |     8 |    28 |
| libraries/libc.a       |  48627 |  2212 |    56 |
| libraries/libgcc.a     |   8120 |     0 |     0 |
| libraries/libm.a       |     88 |     0 |     0 |
| libraries/libnosys.a   |     32 |     0 |     0 |
| libraries/libstdc++.a  |   7758 |    20 |  2176 |
| Subtotals              | 240343 |  2556 | 31364 |
+------------------------+--------+-------+-------+
```

- *ARMCC*
 - No info about libraries? (compared to gcc output)
 - Features / drivers? It's not being shown!

```
+-----------+--------+-------+-------+
| Module    |  .text | .data |  .bss |
+-----------+--------+-------+-------+
| C:/mbed   | 192847 |   727 | 27688 |
| Misc      |  28876 |   103 |  1682 |
| Subtotals | 221723 |   830 | 29370 |
+-----------+--------+-------+-------+
```

- *IAR*
 - same output as armcc
```
+-----------+--------+-------+-------+
| Module    |  .text | .data |  .bss |
+-----------+--------+-------+-------+
| C:/mbed   | 170400 |   450 | 26561 |
| Misc      |  25648 |   620 |   716 |
| Subtotals | 196048 |  1070 | 27277 |
+-----------+--------+-------+-------+
```

**Comment by SeppoTakalo** [comment] 2016-10-11 17:54
Is this really a proper place to collect mbed OS build system related bugs?
Should we collect these in mbed-OS repo as I don't think this is client related?

(I'm not meaning this isn't a valid bug, its a good finding).

**Comment by MarceloSalazar** [comment] 2016-10-11 18:15
This is what I thought but we were told to raise in the oob examples.
@sg- what do you think?

**Comment by sg-** [comment] 2016-10-11 22:28
This is the right place and if not resolved by release it will get moved to the owner location. @theotherjimmy @c1728p9

**Comment by c1728p9** [comment] 2016-10-12 17:10
It looks like this PR introduced this regression:
https://github.com/ARMmbed/mbed-os/pull/2918

**Comment by sg-** [comment] 2016-10-13 13:19
Should be fixed with RC3

**Closed** 2016-10-14 14:00 UTC
